### ISSUE TITLE
Naver repro and model sync

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#1058] opened 2022-03-02 15:22 UTC
@justram will do a repro of all our Naver models just to double check that everything works.

And then sync w/ https://europe.naverlabs.com/research/machine-learning-and-optimization/splade-models/

See if there's anything missing that should be brought into pyserini.

**Comment by justram** [comment] 2022-03-02 16:05
Here is a brief summary:

1. Existing functionality
- [ ] Anserini reproduction with pre-encoded MS MARCO collection
- [ ] Pyserini reproduction with pre-encoded MS MARCO collection

2. Missing functionality
- [ ] SpladeDocument encoder for fully integrated indexing pipeline [ref](https://github.com/naver/splade/tree/main/anserini_evaluation)
- [ ] New pretrained checkpoints (the variants trained with co-condenser, S-BERT hard negatives, and S-BERT cross-encoder distillation) in the [website](https://europe.naverlabs.com/research/machine-learning-and-optimization/splade-models) of Naver
- [ ] BEIR reproduction guide
- [ ] Training codes


It seems like only the last two items are out of the scope of Pyserini / Anserini.
Should I create a new reproduction doc for a fully integrated indexing pipeline, or should I just add new sections in the existing ones to address it? @lintool @MXueguang

**Comment by lintool** [comment] 2022-03-02 16:08
> It seems like only the last two items are out of the scope of Pyserini / Anserini.

Agreed.

> Should I create a new reproduction doc for a fully integrated indexing pipeline, or should I just add new sections in the existing ones to address it?

New docs, I think. We currently have a one-page-per-model structure.

**Comment by justram** [comment] 2022-03-07 15:18
Reproduced results:
![splade_repro_0305](https://user-images.githubusercontent.com/21036667/157060810-d11fe3a6-6341-44b5-b13a-c629e7c175a0.png)
There are tiny differences in the MS MARCO dev subset evaluation.

Probably due to the limitation of integer document encoding of Lucene.
The numbers reported on Naver's website were from the exact searches using float encoding.

**Comment by NThakur20** [comment] 2022-03-07 15:30
I am working on their provided training code and training a splade (distilspade_max) model. Will evaluate the trained model on MSMARCO-dev and provide the reproduction results in the sparse neural benchmarking project.

Kind Regards,
Nandan

**Comment by NThakur20** [comment] 2022-03-07 15:43
For evaluation of [distilSplade_max](https://github.com/naver/splade/tree/main/weights/distilsplade_max) on BEIR datasets, I evaluated using the example codes mentioned in the toolkit: https://github.com/NThakur20/sparse-retrieval/tree/main/examples/inference/distilsplade_max/beir_scifact.

BEIR passages have not been preprocessed to fix the encoding issue and achieve a score of 0.728 NDCG@10 on this TREC-DL 2019 dataset. I think the table in Anserini reports 0.729.

**Comment by justram** [comment] 2022-05-03 11:26
The reproduction is done, close the issue.

**Closed by justram** 2022-05-03 11:26 UTC
