### ISSUE TITLE
version conflict： the doc of experiments-nfcorpus.md

### ISSUE THREAD

**Issue by Adeshen** [castorini/pyserini#1865] opened 2024-04-17 08:17 UTC
It says that 
```
python -m pyserini.encode \
  input   --corpus collections/nfcorpus/corpus.jsonl \
          --fields title text \
  output  --embeddings indexes/nfcorpus.bge-base-en-v1.5 \
          --to-faiss \
  encoder --encoder BAAI/bge-base-en-v1.5 **--l2-norm** \
          --device cpu \
          --pooling mean \
          --fields title text \
          --batch 32

python -m pyserini.encode \
  input   --corpus collections/nfcorpus/corpus.jsonl \
          --fields title text \
  output  --embeddings indexes/nfcorpus.bge-base-en-v1.5 \
          --to-faiss \
  encoder --encoder BAAI/bge-base-en-v1.5 --l2-norm \
          --device cpu \
          --pooling mean \
          --fields title text \
          --batch 32

```
but in the latest version,  it could find  **--l2-norm --pooling mean**

I think  the maintainers maybe forget the issue

**Comment by lintool** [comment] 2024-04-17 12:23
@MXueguang this is related to a recent PR you worked on?

**Comment by MXueguang** [comment] 2024-04-17 16:31
sorry @Adeshen, I didn't get what the issue is, could you explain a bit more details.

**Comment by lintool** [comment] 2024-06-18 10:38
Having heard no further follow-up, closing.

**Closed by lintool** 2024-06-18 10:38 UTC
