### ISSUE TITLE
Fetch title of documents in Robust04

### ISSUE THREAD

**Issue by Pourbahman** [castorini/pyserini#748] opened 2021-08-29 09:20 UTC
Hi,

I used the following link to fetch **title of each doc in Robust04.**

https://colab.research.google.com/github/castorini/anserini-notebooks/blob/master/pyserini_covid19_default.ipynb#scrollTo=yFZlcqEX0t1f 

 I tried different versions of pyserini but in all of them I received the following error when I import pysearch from pyserini.search:

ImportError: cannot import name 'JSearcher' from 'pyserini.pyclass' (/usr/local/lib/python3.7/dist-packages/pyserini/pyclass.py)

Would you please guide me?

Thanks in advance,
Zahra

**Comment by Pourbahman** [comment] 2021-09-09 14:46
Hi,

Kindly, it is about 11 days that I did not get any response. Would you please answer my question since I am a user of what you developed?

Thanks in advance,
Kind Regards,
Zahra

**Comment by lintool** [comment] 2021-09-10 20:06
Duplicate of https://github.com/castorini/anserini/issues/1628

Hi @Pourbahman - the answer to your question is right on the main page of our README: https://github.com/castorini/pyserini/#how-do-i-fetch-a-document

**Closed by lintool** 2021-09-10 20:06 UTC
