### ISSUE TITLE
Incorrect encoding on Windows

### ISSUE THREAD

**Issue by stekiri** [castorini/pyserini#770] opened 2021-09-21 15:22 UTC
When using pyserini under Windows, it seems that the encoding of strings is breaking when passed to the JNI via the [pyjnius](https://github.com/kivy/pyjnius) package.

It happens when a string is encoded as UTF-8 like this `JString(my_str.encode('utf-8'))` (e.g., https://github.com/castorini/pyserini/blob/master/pyserini/search/_searcher.py#L114). It only occurs under Windows as it must collide with the default Windows encoding `CP-1252`.

I [discussed this issue](https://discord.com/channels/423249981340778496/670954391641128960/889782470403293185) with the maintainers of `pyjnius` and it seems that to make it work independently from the platform, the `.encode('utf-8')` could simply be dropped.

Was there a reason why this manual encoding was used in `pyserini`?

I created a branch with the [changes](https://github.com/castorini/pyserini/compare/master...stekiri:encoding-fix?expand=1), I could do a PR if you wish.

**Comment by stekiri** [comment] 2021-09-21 16:10
In fact, it can also be fixed by setting `set _JAVA_OPTIONS=-Dfile.encoding=UTF-8` as mentioned [here](https://github.com/castorini/pyserini/blob/master/docs/installation.md#troubleshooting-tips). The Java option is indeed a bit confusing as it is not only about files, but also about other internals apparently 😞

I am wondering what the best solution for this one is 🤔

If dropping the `.encode('utf-8')` works well under all platforms, it has the advantage that no platform-specific setup is required and, therefore, it will be easier to use (no one will forget to set this param). If the encoding is indeed required, I strongly suggest to make this requirement for Windows user a lot more visible. Maybe in an extra section of the [package installation](https://github.com/castorini/pyserini#package-installation)?

**Comment by lintool** [comment] 2021-09-21 16:56
Hi @stekiri - thanks for raising this issue!

My memory is a bit fuzzy here, but `.encode('utf-8')` was in response to an earlier underlying issue with pyjnius. If pyjnius has address this issue in a platform independent manner, then, yes, we should probably remove in pyserini.

Would you mind sending a PR to that effect? It'd be great if you also included a test case that would catch this issue in the future.

I'll run our suite of regression tests and see if anything is broken... there are queries with non-ASIIC encoding in, for example, MS MARCO - we need to confirm that this doesn't break anything...

Thanks in advance!

**Comment by stekiri** [comment] 2021-09-22 09:31
I looked a bit into the PR/commit history to better understand this 🕵️ 

Please, correct me if I got it wrong 😉 

The original issue was that it wasn't possible to use special characters in jnius ([issue](https://github.com/kivy/pyjnius/issues/437) and [PR](https://github.com/kivy/pyjnius/pull/524)). The changes are present in `pyjnius>=1.3.0` ([jnius_conversion.pxi](https://github.com/kivy/pyjnius/blob/1.3.0/jnius/jnius_conversion.pxi)).

In `pyserini`, it was fixed by adding `.encode('utf-8')` in a couple of places (see [PR](https://github.com/castorini/pyserini/pull/50)). @PepijnBoers wrote a [test case](https://github.com/castorini/pyserini/pull/50/files#diff-ac54deb245f5dac55a676ddf50894261299ae163cf2616f4f0700931b6e92d63R128) to remind us that the underlying issue was fixed in `pyjnius` and, therefore, the `.encode('utf-8')` workaround would not have been necessary anymore (see [comment](https://github.com/castorini/pyserini/pull/50#issuecomment-595859489)).

This test case was indeed removed in this [PR](https://github.com/castorini/pyserini/pull/375), but the `.encode('utf-8')` was not removed at the same time. With hindsight, I think it would have been good to add `pyjnius>=1.3.0` into the `requirements.txt` at this time, but this is not a biggie.

The issue popped up once more for you [here](https://github.com/castorini/pyserini/pull/411), you may have still
had `pyjnius==1.2.1` in your virtual environment, so you also fixed this by adding `.encode('utf-8')`.

If I got this all correct, I think the changes could be:
1. Bump `pyjnius` in `requirements.txt` to `>=1.3.0`.
2. All occurrences of `.encode('utf-8')` can now simply be removed.
3. (Optional as I am not convinced if it is actually a useful test) A test case that creates `JString('ö')` succesfully (i.e., the reverse case of the previously existing test).

Let me know what you think and then I'll do the PR.

**Comment by lintool** [comment] 2021-09-23 10:53
Yup, I agree - this is a great course of action!

Just for completeness, can we add test case per (3) and in the comments reference this awesome issue that summarizes the progressions of the issues?

Thanks so much!

**Comment by lintool** [comment] 2021-10-04 22:22
Closed by #795

**Comment by yuki617** [comment] 2021-10-29 18:24
@stekiri @lintool Just added a minimal test tests.test_index_reader.test_doc_vector_emoji_test which encapsulates this emoji encoding issue. Ready to move on for further discussion.

**Comment by lintool** [comment] 2021-10-29 19:06
I worked on the test case a bit more here: #847

**Comment by lintool** [comment] 2021-10-30 19:24
Hi @stekiri it does seem like we have to revert #795 and add `.encode('utf-8')` back in?

> In fact, it can also be fixed by setting `set _JAVA_OPTIONS=-Dfile.encoding=UTF-8` as mentioned [here](https://github.com/castorini/pyserini/blob/master/docs/installation.md#troubleshooting-tips). The Java option is indeed a bit confusing as it is not only about files, but also about other internals apparently 😞

It seems like the fix is to clarify in documentation, per above?

Thoughts?

Let's all sit on this for a few days... but not too long, because I'd like to cut a pypi release soon-ish.

**Comment by stekiri** [comment] 2021-11-03 19:27
@lintool, I looks indeed like the `pyjnius` package does not deal correctly with emojis. It's possible to make your test pass if you change [this line](https://github.com/castorini/pyserini/blob/5469a399fe77504bfd6043cc7400746e97754659/pyserini/index/_base.py#L299) to:

```
term_map = self.object.getTermCountsWithAnalyzer(self.reader, term, analyzer)
```

And [this line](https://github.com/castorini/pyserini/blob/5469a399fe77504bfd6043cc7400746e97754659/pyserini/index/_base.py#L352) to:

```
doc_vector_dict[term] = doc_vector_map.get(term)
```

So, simply remove the manual `JString` wrapping. I don't know why it is the case, the maintainers of the `pyjnius` package will probably have an answer.

You can also reproduce it with a more minimal example like this:

Create a simple Java class like this one in `anserini`: `src/main/java/io/anserini/search/EncTest.java`

```
package io.anserini.search;

public class EncTest {
    public String sendBack(String in) {
        System.out.println(in);
        return in;
    }
}

```

On Python side:
```
from jnius import autoclass

JString = autoclass('java.lang.String')
EncTest = autoclass('io.anserini.search.EncTest')

print('Only emoji:\n')
print(EncTest().sendBack('😞'))

print('With JString:\n')
print(EncTest().sendBack(JString('😞')))
```

It outputs the following:

```
Only emoji:
😞
😞
With JString:


```

For this particular case it seems that it is solvable this way, but does it mean that all the occurrences of `JString` should be removed and we should always fallback to the automatic conversion of pyjnius? I guess the maintainers of that package would have an answer to this.

The ideal fix would probably be that the issue is addressed in the pyjnius package and then we use the fixed version. Until then, it seems like adding `.encode('utf-8')` back seems to be the less risky fix.

**Comment by lintool** [comment] 2021-11-03 20:01
@stekiri I like the solution of just killing all the `JString` wrapping... if it doesn't break any of our regressions tests (beyond just what the test case exposes)...

Do you have the cycles to send a PR along those lines? If not, we can ask @yuki617 .

**Comment by lintool** [comment] 2021-11-05 11:24
Final wrap-up #863

**Closed by lintool** 2021-11-05 11:24 UTC
