### ISSUE TITLE
Multiple language support?

### ISSUE THREAD

**Issue by velocityCavalry** [castorini/pyserini#565] opened 2021-05-13 07:05 UTC
Hi,

Does pyserini currently support languages other than language? Specifically, I am asking about using features such as creating an index by  `python -m pyserini.index -collection JsonCollection -generator DefaultLuceneDocumentGenerator ...` and using `searcher.search`. If yes, how do I integrate it in python script?

Thank you!

**Comment by lintool** [comment] 2021-05-13 11:28
Yup, we support a number of languages - zh, ar, fr, etc.

See the multi-lingual regressions here: https://github.com/castorini/anserini#regression-experiments

What are your needs specifically?

**Comment by velocityCavalry** [comment] 2021-05-13 12:39
> Yup, we support a number of languages - zh, ar, fr, etc.
> 
> See the multi-lingual regressions here: https://github.com/castorini/anserini#regression-experiments
> 
> What are your needs specifically?

I have a wikipedia dump that is in Japanese, and I would like to index it using pyserini and search it with queries in Japanese as well.

Currently I am indexing it using ` python -m pyserini.index -collection JsonCollection -generator DefaultLuceneDocumentGenerator -threads 8  -input <the path to the wiki dump> -index <the path to store the indexes> -storePositions -storeDocvectors -storeRaw` and searching it using 
```
from pyserini.search import SimpleSearcher
searcher = SimpleSearcher(<the path to the indexes>)
hits = searcher.search(<query>)
```
Seems that `pyserini.index` is capable of using `--language` flag to specify the language, but for `SimpleSearcher`, is there a way to specify the language as well?

Thank you so much!

**Comment by lintool** [comment] 2021-05-13 14:34
Unfortunately, we don't have the bindings exposed for jp, the closest is zh, but in Anserini - see:
https://github.com/castorini/anserini/blob/master/docs/regressions-ntcir8-zh.md

Fortunately, Lucene does support jp:
https://lucene.apache.org/core/8_0_0/analyzers-kuromoji/org/apache/lucene/analysis/ja/JapaneseTokenizer.html

This will require a few code changes, around here:
https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexCollection.java#L738

So, shouldn't be too hard...

If you decided to take this route, we'd appreciate a PR to have the functionality merged back.

**Comment by velocityCavalry** [comment] 2021-05-14 00:33
> Unfortunately, we don't have the bindings exposed for jp, the closest is zh, but in Anserini - see:
> https://github.com/castorini/anserini/blob/master/docs/regressions-ntcir8-zh.md
> 
> Fortunately, Lucene does support jp:
> https://lucene.apache.org/core/8_0_0/analyzers-kuromoji/org/apache/lucene/analysis/ja/JapaneseTokenizer.html
> 
> This will require a few code changes, around here:
> https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexCollection.java#L738
> 
> So, shouldn't be too hard...
> 
> If you decided to take this route, we'd appreciate a PR to have the functionality merged back.

When I try to add import statements such as `import org.apache.lucene.analysis.ja.JapaneseAnalyzer;` to files like `src/main/java/io/anserini/index/IndexCollection.java`, when try to rebuild anserini using `mvn clean package appassembler:assemble`, it will spit out errors below. Do I need to add any additional build instruction to any other files as well?

Thanks!

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project anserini: Compilation failure
[ERROR] ~/anserini/src/main/java/io/anserini/index/IndexCollection.java:[58,37] package org.apache.lucene.analysis.ja does not exist
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by lintool** [comment] 2021-05-14 14:39
You probably need this artifact: https://search.maven.org/search?q=a:lucene-analyzers-kuromoji

See: https://lucene.apache.org/core/8_0_0/

(Find the right version to match Anserini's)

**Comment by velocityCavalry** [comment] 2021-05-16 06:51
> You probably need this artifact: https://search.maven.org/search?q=a:lucene-analyzers-kuromoji
> 
> See: https://lucene.apache.org/core/8_0_0/
> 
> (Find the right version to match Anserini's)

Sorry, I am not really familiar with apache...Does it require me to add something like `<artifactId>lucene-analyzers-kuromoji</artifactId>` around [line 278 in pom.xml](https://github.com/castorini/anserini/blob/2591e063b4bee8881a641cf2167352ac212865a6/pom.xml#L278)?

**Comment by lintool** [comment] 2021-05-16 18:39
Yes, exactly!

**Comment by velocityCavalry** [comment] 2021-05-19 07:05
> Yes, exactly!

Thank you for the instruction! 

I do have one more question, say if I want to index and search my own documents in Arabic (which is supported in Anserini)) using pyserini, is 
```
python -m pyserini.index -collection JsonCollection -language ar -generator DefaultLuceneDocumentGenerator \
 -threads 8  -input <path to the arabic document> -index <output path> -storePositions  -storeDocvectors -storeRaw
```
the correct way? 

Also, during searching, can I just do `hits = searcher.search(query, k=10)` without specifying the language code to be `ar`? Moreover, do I need to change the tokenizer in [tokenize_json_collection.py](https://github.com/castorini/pyserini/blob/a9d6f66234b5dd2859a0dc116ef3e38a52d0f81d/pyserini/tokenize_json_collection.py) to be `bert-base-multilingual-cased` rather than `bert-base-uncased`? 

Thank you so much!

**Comment by lintool** [comment] 2021-05-19 08:44
@crystina-z can you help with `ar` searching here?

**Comment by crystina-z** [comment] 2021-05-19 14:27
@velocityCavalry Hi there! Yup that indexing script looks right to me.

For the searching, I believe the language can be specified by doing things like
```
analyzer = get_lucene_analyzer(name="Arabic")
searcher.set_analyzer(analyzer)
hits = searcher.search(query, k=10)
```

And yes, the `bert-base-uncased` would need to be changed.

**Comment by velocityCavalry** [comment] 2021-05-19 20:01
> @velocityCavalry Hi there! Yup that indexing script looks right to me.
> 
> For the searching, I believe the language can be specified by doing things like
> 
> ```
> analyzer = get_lucene_analyzer(name="Arabic")
> searcher.set_analyzer(analyzer)
> hits = searcher.search(query, k=10)
> ```
> 
> And yes, the `bert-base-uncased` would need to be changed.

I really appreciate your fast response! Though I wonder why the tokenizer in [tokenize_json_collection.py](https://github.com/castorini/pyserini/blob/a9d6f66234b5dd2859a0dc116ef3e38a52d0f81d/pyserini/tokenize_json_collection.py) needs to be change, while in [this line](https://github.com/castorini/pyserini/blob/ecfe4e9c32d151d2cac58292ff952288e8b103f2/pyserini/search/__main__.py#L154) in `pyserini/search/__main__.py` doesn't need be changed/specified and there is not a default tokenizer such as `bert-base-multilingual-cased`. 

Moreover, it seems that the languages currently supported by pyserini are `ar, es, de, zh, hi, en` based on [this file](https://github.com/castorini/pyserini/blob/784a30d7bc208ad3b01242490ca076dfd9e1214c/pyserini/analysis/_base.py). If the documents are not in any of these languages and I index and search them, what's the expected behavior?

**Comment by lintool** [comment] 2021-05-19 20:12
> I really appreciate your fast response! Though I wonder why the tokenizer in [tokenize_json_collection.py](https://github.com/castorini/pyserini/blob/a9d6f66234b5dd2859a0dc116ef3e38a52d0f81d/pyserini/tokenize_json_collection.py) needs to be change, while in [this line](https://github.com/castorini/pyserini/blob/ecfe4e9c32d151d2cac58292ff952288e8b103f2/pyserini/search/__main__.py#L154) in `pyserini/search/__main__.py` doesn't need be changed/specified and there is not a default tokenizer such as `bert-base-multilingual-cased`.

For what you need,  `tokenize_json_collection.py` doesn't need to be changed... that's for another experimental feature @crystina-z is working on.

> Moreover, it seems that the languages currently supported by pyserini are `ar, es, de, zh, hi, en` based on [this file](https://github.com/castorini/pyserini/blob/784a30d7bc208ad3b01242490ca076dfd9e1214c/pyserini/analysis/_base.py). If the documents are not in any of these languages and I index and search them, what's the expected behavior?

Pyserini just provides bindings to analyzers already available in Lucene, see here: https://lucene.apache.org/core/8_0_0/

See `analyzer-*` if you want to use them, you'll need to enable them in Anserini (for the indexing) - like here: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexCollection.java#L740 and then in the file you referenced above (for the retrieval).

**Comment by crystina-z** [comment] 2021-05-19 20:53
@velocityCavalry oh sorry I misunderstood. yes if just to use current `index` and `search`, then dunno need to change that file at all.

**Comment by velocityCavalry** [comment] 2021-05-20 04:30
> > I really appreciate your fast response! Though I wonder why the tokenizer in [tokenize_json_collection.py](https://github.com/castorini/pyserini/blob/a9d6f66234b5dd2859a0dc116ef3e38a52d0f81d/pyserini/tokenize_json_collection.py) needs to be change, while in [this line](https://github.com/castorini/pyserini/blob/ecfe4e9c32d151d2cac58292ff952288e8b103f2/pyserini/search/__main__.py#L154) in `pyserini/search/__main__.py` doesn't need be changed/specified and there is not a default tokenizer such as `bert-base-multilingual-cased`.
> 
> For what you need, `tokenize_json_collection.py` doesn't need to be changed... that's for another experimental feature @crystina-z is working on.
> 
> > Moreover, it seems that the languages currently supported by pyserini are `ar, es, de, zh, hi, en` based on [this file](https://github.com/castorini/pyserini/blob/784a30d7bc208ad3b01242490ca076dfd9e1214c/pyserini/analysis/_base.py). If the documents are not in any of these languages and I index and search them, what's the expected behavior?
> 
> Pyserini just provides bindings to analyzers already available in Lucene, see here: https://lucene.apache.org/core/8_0_0/
> 
> See `analyzer-*` if you want to use them, you'll need to enable them in Anserini (for the indexing) - like here: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexCollection.java#L740 and then in the file you referenced above (for the retrieval).

Thanks for all of the instructions! Though the search feature cannot be completed smoothly.  

The steps I follow:

1. add `import org.apache.lucene.analysis.da.DanishAnalyzer;` and the if-checks for `args.language` in `Public SearchCollection` in anserini/src/main/java/io/anserini/search/SearchCollection.java
2. add `import org.apache.lucene.analysis.da.DanishAnalyzer;` and `final DanishAnalyzer danishAnalyzer = new DanishAnalyzer();` and the if checks for `args.language` in `public Counters run()`  in anserini/src/main/java/io/anserini/index/IndexCollection.java
3. add `import org.apache.lucene.analysis.da.DanishAnalyzer;` and the if-checks for language in `setLanguage()` in src/main/java/io/anserini/search/SimpleSearcher.java
4. add `JDanishAnalyzer = autoclass('org.apache.lucene.analysis.da.DanishAnalyzer')` and accordingly add the if-checks in `get_lucene_analyzer()` in  pyserini/analysis/_base.py
5. follow the development setup page for pyserini & anserini -- all unit tests passed and maven successfully built
6. index the Danish document using `python -m pyserini.index -collection JsonCollection -language da -generator DefaultLuceneDocumentGenerator -threads 8  -input <danish document input path -index <output path> -storePositions \
 -storeDocvectors -storeRaw;` -- no errors 
7. search using: 
```
from pyserini.search import SimpleSearcher
searcher = SimpleSearcher(<index output path>)
analyzer = analysis.get_lucene_analyzer(name="Danish")
searcher.set_analyzer(analyzer)
hits = searcher.search('hvem har de fleste følgere på instagram')
```

It will give something like 
```
  File "~/pyserini/pyserini/search/_searcher.py", line 130, in search
    hits = self.object.search(JString(q.encode('utf8')), k)
  File "jnius/jnius_export_class.pxi", line 1145, in jnius.JavaMultipleMethod.__call__
  File "jnius/jnius_export_class.pxi", line 857, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 947, in jnius.JavaMethod.call_method
  File "jnius/jnius_jvm_dlopen.pxi", line 91, in jnius.create_jnienv
jnius.JavaException: JVM exception occurred: java.lang.NullPointerException
```

Is there anything else that I am missing? It seems to work fine with languages that are currently supported by pyserini/anserini, but I don't think they are working with any of the languages that I've added in, though I add Danish to every place where "German" occurs (I think). 

Thank you so so much! (And sorry about these lengthy questions!)

**Closed** 2021-05-20 08:25 UTC

**Comment by Fatima-Haouari** [comment] 2022-01-11 16:19
> > > I really appreciate your fast response! Though I wonder why the tokenizer in [tokenize_json_collection.py](https://github.com/castorini/pyserini/blob/a9d6f66234b5dd2859a0dc116ef3e38a52d0f81d/pyserini/tokenize_json_collection.py) needs to be change, while in [this line](https://github.com/castorini/pyserini/blob/ecfe4e9c32d151d2cac58292ff952288e8b103f2/pyserini/search/__main__.py#L154) in `pyserini/search/__main__.py` doesn't need be changed/specified and there is not a default tokenizer such as `bert-base-multilingual-cased`.
> > 
> > 
> > For what you need, `tokenize_json_collection.py` doesn't need to be changed... that's for another experimental feature @crystina-z is working on.
> > > Moreover, it seems that the languages currently supported by pyserini are `ar, es, de, zh, hi, en` based on [this file](https://github.com/castorini/pyserini/blob/784a30d7bc208ad3b01242490ca076dfd9e1214c/pyserini/analysis/_base.py). If the documents are not in any of these languages and I index and search them, what's the expected behavior?
> > 
> > 
> > Pyserini just provides bindings to analyzers already available in Lucene, see here: https://lucene.apache.org/core/8_0_0/
> > See `analyzer-*` if you want to use them, you'll need to enable them in Anserini (for the indexing) - like here: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexCollection.java#L740 and then in the file you referenced above (for the retrieval).
> 
> Thanks for all of the instructions! Will merge my change once I have time



> > > I really appreciate your fast response! Though I wonder why the tokenizer in [tokenize_json_collection.py](https://github.com/castorini/pyserini/blob/a9d6f66234b5dd2859a0dc116ef3e38a52d0f81d/pyserini/tokenize_json_collection.py) needs to be change, while in [this line](https://github.com/castorini/pyserini/blob/ecfe4e9c32d151d2cac58292ff952288e8b103f2/pyserini/search/__main__.py#L154) in `pyserini/search/__main__.py` doesn't need be changed/specified and there is not a default tokenizer such as `bert-base-multilingual-cased`.
> > 
> > 
> > For what you need, `tokenize_json_collection.py` doesn't need to be changed... that's for another experimental feature @crystina-z is working on.
> > > Moreover, it seems that the languages currently supported by pyserini are `ar, es, de, zh, hi, en` based on [this file](https://github.com/castorini/pyserini/blob/784a30d7bc208ad3b01242490ca076dfd9e1214c/pyserini/analysis/_base.py). If the documents are not in any of these languages and I index and search them, what's the expected behavior?
> > 
> > 
> > Pyserini just provides bindings to analyzers already available in Lucene, see here: https://lucene.apache.org/core/8_0_0/
> > See `analyzer-*` if you want to use them, you'll need to enable them in Anserini (for the indexing) - like here: https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexCollection.java#L740 and then in the file you referenced above (for the retrieval).
> 
> Thanks for all of the instructions! Will merge my change once I have time

Hi,
Could you please help with the following:
I managed to index my Arabic documents by specifying -language ar as you mentioned above. However when I tried to specify the language to search as shown below I am getting the following error     
```
searcher.set_language('ar')
AttributeError: 'SimpleSearcher' object has no attribute 'set_language'
```

Here is the code
```
from pyserini.search import SimpleSearcher
searcher=SimpleSearcher('indexes/bio_description_lists_index')
searcher.set_language('ar')

```
Please advise.

**Comment by lintool** [comment] 2022-01-11 17:44
Duplicate of #932
