### ISSUE TITLE
MS MARCO V1 Passage in Linux Student Environment (Encountered Issues with SLIM)

### ISSUE THREAD

**Issue by yilinjz** [castorini/pyserini#1635] opened 2023-09-13 23:01 UTC
Tried the following command in the student environment (reference: https://castorini.github.io/pyserini/2cr/msmarco-v1-passage.html). 
`python -m pyserini.2cr.msmarco --collection v1-passage --all --display-commands`
which downloads ~350 gb work of indexes. <br>
(For repro: make sure to run `ulimit -t unlimited` first as the CPU would timeout otherwise.)

The commands took about 6 hours to finish on the student env. Result screenshot:

<img width="935" alt="pyserini_2cr_msmarco" src="https://github.com/castorini/pyserini/assets/71229867/10d2733a-e3db-4ca0-8541-9377d4ecb3f8">

As shown, SLIM had issues running on the student environment. 
<img width="1332" alt="Screenshot 2023-09-05 at 6 32 19 PM" src="https://github.com/castorini/pyserini/assets/71229867/2046ce21-3468-486a-814f-6a69311e13b8">

**Comment by yilinjz** [comment] 2023-09-13 23:04
Our current speculation is that slim tries to load a bunch of vectors in memory which caused an OOM error. <br>
However, the student environment seems to provide sufficient memory (~512 GB)...
<img width="583" alt="Screenshot 2023-09-06 at 5 53 16 PM" src="https://github.com/castorini/pyserini/assets/71229867/34db0a8d-0fa3-4bf1-82c7-c30dc3dca688">

**Comment by yilinjz** [comment] 2023-09-13 23:05
For future repro: make sure to run `ulimit -t unlimited` first as the CPU would timeout otherwise.

**Comment by lintool** [comment] 2023-09-13 23:42
@yilinjz thanks, good to know.

**Comment by yilinjz** [comment] 2023-09-15 15:38
Update: CSCF has confirmed that the SIGKILL failures are due to memory usage caps on student Linux env.

**Comment by lintool** [comment] 2023-09-18 02:26
I think we can close this issue as the issue is with the env, not with any issues with the Pyserini 2CR.

**Closed by lintool** 2023-09-18 02:26 UTC
